### ISSUE TITLE
Test failures in browsers on HDPI displays

### ISSUE THREAD

**Issue by iangilman** [openseadragon/openseadragon#1000]
Our test suite runs well in the terminal, but when run in a browser we have several failures. Seems worth sorting out!

In Mac Chrome I'm getting three failures in "Multi-Image: Transparent image on top of others" and two in "TiledImage: clip".

In Mac Firefox, the suite doesn't even complete because of:

```
Events: Viewer: preventDefaultActionRerun

    ReferenceError: event is not defined@ 23 ms
    Source: 	

    http://localhost:8000/test/modules/events.js:764
```
