### ISSUE TITLE
controlAnchor positioning within toobar? 

### ISSUE THREAD

**Issue by SamHall** [openseadragon/openseadragon#1153]
I find the default button 'containers' work very well and would like to use them in the toolbar when I have to include other controls in full screen mode. However, I cannot find the right 'magic' to position them to the top right. Using controlArchor works in the canvas, but has no effect in the toolbar. 
I've attempted throwing CSS at it - but the javascript overrides it.

Example with default button container (with custom PNGs) in the toolbar, forced to the top-left:
http://deepzoomchattanooga.com/realestate_debug

**Comment by iangilman** [comment]
That's an awesome page! 

So you're using an OpenSeadragon.ControlDock? And you're calling addControl to it? Are you passing in OpenSeadragon.ControlAnchor.TOP_RIGHT? Would you mind making a codepen or something reproducing the issue?

**Comment by SamHall** [comment]
I've cleaned up that link to include only the needed code. The issue is my lack of knowledge in javascript. I've trying to use it like the navigatorPosition option, but am not understanding the need / usage for addControl. 



Relevant code below: 
```
<script type="text/javascript">
              var viewer = new OpenSeadragon.Viewer({
                id: "openseadragon-canvas",
                toolbar: "toolbarDiv",
                prefixUrl: "/openseadragon/images_TEST/",
                tileSources: [
                  "/zoom/600market.dzi",
                  "/zoom/601market.dzi",
                  "/zoom/700_market.dzi",
                  "/zoom/701market.dzi",
                  "/zoom/800market.dzi",
                  "/zoom/801market.dzi"
                ],
               navigationControlAnchor: OpenSeadragon.ControlAnchor.TOP_RIGHT,
                navigatorPosition: "BOTTOM_RIGHT",
                showNavigator:  true,
                sequenceMode: true,
                showSequenceControl: false,
                showReferenceStrip:  false,
                showZoomControl: true,
                showHomeControl: false,
                constrainDuringPan: true,
                visibilityRatio: 0.8,
                defaultZoomLevel: 1.4,
                maxZoomPixelRatio: 3,
                autoHideControls: false
              }
                                                   );
              $('.pg00').click(function() {
                viewer.goToPage(0);
              }
                              );
              $('.pg01').click(function() {
                viewer.goToPage(1);
              }
                              );
              $('.pg02').click(function() {
                viewer.goToPage(2);
              }
                              );
              $('.pg03').click(function() {
                viewer.goToPage(3);
              }
                              );
              $('.pg04').click(function() {
                viewer.goToPage(4);
              }
                              );
              $('.pg05').click(function() {
                viewer.goToPage(5);
              }
                              );
            </script>

```
And the toolbarDiv is used but not using custom buttons (other than the PNGs that I replaced from the default images path)

```
              <div class="row">
                <div class="col-centered col-lg-10 col-md-12 col-xs-12"> 
                 <div id="toolbarDiv">
                    <div class="col-md-10 col-xs-9">
                      <div class="carousel">
                        <div class="pg00 carousel-cell">
                          <img src="svg/600t.svg" />
                        </div>
                        <div class="pg01 carousel-cell"> 
                          <img src="svg/601t.svg" />
                        </div>
                        <div class="pg02 carousel-cell">
                          <img src="svg/700t.svg" />
                        </div>
                        <div class="pg03 carousel-cell">
                          <img src="svg/701t.svg" />
                        </div>
                        <div class="pg04 carousel-cell"> 
                          <img src="svg/800t.svg" />
                        </div>
                        <div class="pg05 carousel-cell"> 
                          <img src="svg/801t.svg" />
                        </div>
                      </div>
                    </div> 
                    <div class="col-md-2 col-xs-3">
                    </div>
                  </div> 
                </div> 
              </div> 
```

**Comment by iangilman** [comment]
Okay, this gives me a better idea of what you're doing... never mind the addControl thing. Now I just need to get a better idea of what you're trying to accomplish. Do you just want your carousel of buttons to go against the right rather than bumping into the OSD controls that are on the left? Or do you want the OSD controls to go to the right?

At any rate, I think it is just a matter of CSS. For instance if you want the carousel to go to the right, you can add a `float: right` to the `col-md-10 col-xs-9` that contains it.

**Comment by SamHall** [comment]
Actually I want the OSD controls to be on the right, in the toolbarDiv.
I can move the carousel of buttons around fine, and have left room for the OSD buttons on the right.
navigationControlAnchor: OpenSeadragon.ControlAnchor.TOP_RIGHT,
Works fine when the OSD buttons are used in the 'canvas', but this doesn't work in the toolbarDiv.

**Comment by comrade2sun** [comment]
Hi SamHall

I dit create a custom toolbar a while ago _(<a href="http://homepage.o2mail.de/nixneues/cojp/test.html">OSD Image Gallery - TEST</a>)_ and stumbled in the same trouble as You do now.
You may try this set up with an unordered list for your custom buttons
#### The HTML

``` html
<div id="toolbarDiv" class="toolbar">
    <div class="col-md-10 col-xs-9">
        <div class="carousel">
            <!-- ... -->
        </div>
    </div>
	<div class="col-md-2 col-xs-3"> <!-- I guess this is the container for Your buttons -->
<!-- 	This may ... -->
    <ul id="menu-bar">
        <li>
            <a id="zoom-in" class="zoomin" href="#zoom-in"></a>
        </li>
        <li>
            <a id="zoom-out" class="zoomout" href="#zoom-out"></a>
        </li>
        <li>
            <a id="full-page" class="fullscreen" href="#full-page"></a>
        </li>
    </ul>
<!--	... (or may not) do the magic  -->
	</div>
</div>
```

#### The OSD 
``` javascript
var viewer = new OpenSeadragon.Viewer({
        id: "openseadragon-canvas",
		toolbar: "toolbarDiv",
		zoomInButton : "zoom-in",
		zoomOutButton : "zoom-out",
		fullPageButton : "full-page"
		...
```

#### The CSS

Use the class` .toolbar` and a class  `.toolbar.fullpage` for the fullscreen-mode to position _( z-index: 10;)_ the "toolbarDiv"

Get Your custom icons similar like this:
``` css
a.zoomin {
    background: url('../img/icons/zoom-in.png')no-repeat center center;
    height: 24px;
}
a.zoomout {
    background: url('../img/icons/zoom-out.png')no-repeat center center;
    height: 24px;
}
a.fullscreen {
    background: url('../img/icons/fullscreen.png')no-repeat center center;
    height: 24px;
}
```

Style your icons 
``` css
ul.tool-bar li a,
.navigation a {
    float: ;
    width: ;
    height: ;
    margin: ;
    cursor: ;
}
```

and the unordered list similar like this, according to your needs

``` css
#menu-bar {
    width: 280px; /* fixed width, change this width as needed */
    display: block;
    margin: 0 auto; /* center the menu-bar*/
    position: relative;
}
#menu-bar li {
    padding: 0 6px;
    float: left;
    position: relative;
    list-style: none;
}
#menu-bar a {
    display: block;
    padding: 6px 20px;
    opacity: 0.6; /* inital opacity */
}
#menu-bar li:hover>a {
	/* little shadow on icons bottom */
    -webkit-box-shadow: 0 1px 1px -1px rgba(17, 81, 128, 1);
    -moz-box-shadow: 0 1px 1px -1px rgba(17, 81, 128, 1);
	opacity: 1; /* set opacity to 1 */
}
#menu-bar:after {
    content: ".";
    display: block;
    clear: both;
    visibility: hidden;
}
```
I hope, this will get you at least an idea how to solve your problem.
Good Luck
