### ISSUE TITLE
Full screen mode: easier styling

### ISSUE THREAD

**Issue by acdha** [openseadragon/openseadragon#61]
Currently the new fullscreen mode - which is awesome - is hard to style because the top-level openseadragon-container element has explicit styles set on it including `background-color: rgba(0,0,0,0);`, which means you're forced to do something like

``` css
.openseadragon-container {
    background-color: black !important;
}
```

What do you think about simply not setting this at all? It's also complicated by the fact that there's no way to detect fullscreen mode currently - I was thinking that we should dynamically toggle a `fullscreen` class on the container element so the above could become:

``` css
.openseadragon-container.fullscreen {
    background-color: black;
}
```
